stages:
  - build
  - push

variables:
  IMAGE_NAME: "$DOCKERHUB_USERNAME/backend-user"  # replace per service
  DOCKER_HOST: tcp://docker:2375
  DOCKER_TLS_CERTDIR: ""

build-and-push:
  stage: build
  image: docker:20.10.16
  services:
    - docker:dind
  script:
    - docker login -u "$DOCKERHUB_USERNAME" -p "$DOCKERHUB_PASSWORD"
    - docker build -t $IMAGE_NAME:latest .
    - docker run --rm $IMAGE_NAME:latest npx prisma generate   
    - docker commit $(docker ps -alq) $IMAGE_NAME:latest      
    - docker push $IMAGE_NAME:latest
  only:
    - main
